version: '3.1'

networks:
  web:

services:

  app:
    dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/html/
    working_dir: /var/www/html/
    command: bash -c "npm install && npm run deploy"
    networks:
      - web

  webserver:
    image: nginx:1.13
    container_name: webserver
    volumes:
      - ./:/var/www/html
      # Configuração para o proxy reveso
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    ports:
      - 8080:80
    depends_on:
      - app

